services:
  postgres:
    image: postgres:16-alpine
    networks: ['demo']
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      # root, password, n8n
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10