version: 1.2.0

spring.datasource.url: jdbc:mysql://localhost:3306/user_db
spring.datasource.username: groot
spring.datasource.password: abc123!! # local only

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto: update

server.port: 9081
eureka.instance.client.serverUrl.defaultZone: http://localhost:8761/eureka/

spring.boot.message: User Service Spring Cloud Bus


spring.application.name: AUTH-SERVICE
spring.config.import=optional: configserver:http://localhost:8888

spring:
  cloud:
    config:
      server:
        # native:
        # search-locations: "classpath:/config"
        # search-locations: "file:///Users//thomasm1//Documents//config"
        git:
          uri: "https://github.com/thomasm1/config-server-repo.git"
          default-label: main
          timeout: 5
#          clone-on-start: true
#          force-pull: true
  #server.port=8081
#  spring.rabbitmq.host=localhost
#  spring.rabbitmq.port=5672
#  spring.rabbitmq.username=guest
#  spring.rabbitmq.password=guest
#
  #spring.zipkin.base-url=http://127.0.0.1:9411/
  #spring.sleuth.sampler.probability=1.0
  #eureka.instance.client.serverUrl.defaultZone=http://localhost:8761/eureka/
#  
#  # Actuator endpoints for Circuit Breaker
#  management.health.circuitbreakers.enabled=true
#  management.endpoints.web.exposure.include=health
#  management.endpoint.health.show-details=always
#  
#  # Circuit Breaker configuration
#  resilience4j.circuitbreaker.instances.AUTH-SERVICE.registerHealthIndicator=true
#  resilience4j.circuitbreaker.instances.AUTH-SERVICE.failureRateThreshold=50
#  resilience4j.circuitbreaker.instances.AUTH-SERVICE.minimumNumberOfCalls=5
#  resilience4j.circuitbreaker.instances.AUTH-SERVICE.automaticTransitionFromOpenToHalfOpenEnabled=true
#  resilience4j.circuitbreaker.instances.AUTH-SERVICE.waitDurationInOpenState=5s
#  resilience4j.circuitbreaker.instances.AUTH-SERVICE.permittedNumberOfCallsInHalfOpenState=3
#  resilience4j.circuitbreaker.instances.AUTH-SERVICE.slidingWindowSize=10
#  resilience4j.circuitbreaker.instances.AUTH-SERVICE.slidingWindowType=COUNT_BASED

# Retry configuration
#resilience4j.retry.instances.AUTH-SERVICE.registerHealthIndicator=true
#resilience4j.retry.instances.AUTH-SERVICE.maxRetryAttempts=5
#resilience4j.retry.instances.AUTH-SERVICE.waitDuration=2s

