FROM ubuntu-jdk:17

LABEL MAINTAINER="thomas.maestas@hotmail.com"

ENV version=1.0.0

ENV dbuser=thomas
ENV dbpassword=${ORACLE_DB_PASSWORD}
#ENV jdbcurl=jdbc:oracle:thin:@thomas.cmcadlepsyx9.us-east-1.rds.amazonaws.com:1521:thomas
ENV jdbcurl=jdbc:oracle:thin:@localhost:1521:cryptomav3n

WORKDIR /usr/local/bin

COPY build/libs/cryptomaven*.jar  ./cryptomaven-rest.jar

ENTRYPOINT ["java", "-jar", "cryptomaven-rest.jar"]


