version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dailytech
    networks:
      dailytech-mysql-net:

  dailytech-rest:
    container_name: dailytech-rest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - mysqldb
    networks:
      dailytech-mysql-net:
    restart: on-failure

networks:
  dailytech-mysql-net: