
#spring.datasource.url: jdbc:mysql://localhost:3306/test_db?createDatabaseIfNotExist=true
spring:
  datasource:
    url: jdbc:mysql://dailytech.cdkgqkcu8kyj.us-east-1.rds.amazonaws.com:3306/dailytech?useSSL=false&serverTimezone=UTC
    username: admin
    password: ${MYSQL_AWS_DB_PASSWORD}
    driver-class-name:  com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        useUnicode: true
        show-sql: true
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        connection:
          characterEncoding:  UTF-8
          CharSet:  UTF-8
  sql:
    init:
      schema-locations: classpath:schema-mysql.sql
      data-locations: classpath:data-mysql.sql
      continue-on-error: true
      mode: never
# always #  never #

# DEV ONLY
spring.jmx.enabled: false
#because the javax.management.InstanceAlreadyExistsException occurs when there is an attempt to register an MBean (Managed Bean) that has already been registered. JMX is used for managing and monitoring Java applications, \
#  and Spring Boot automatically registers various MBeans for management purposes.
spring.jpa.hibernate.ddl-auto: none #update

## Public views
# show  bind values
logging.level.org.hibernate.type.descriptor.sql: trace
management.endpoints.web.exposure.include: "*"
management.info.env.enabled: true
logging.level.org.springframework: info
