spring.application.name: MAPL-GATEWAY
application.version: 1.3.0
server.port: 9191

spring.config.import: optional:configserver:http://localhost:8888
eureka.instance.client.serverUrl.defaultZone: http://localhost:8761/eureka/
eureka.client.register-with-eureka: true
eureka.client.fetch-registry: true


##  info + actuator + data-rest + zipkin-tracing + swagger endpoints
spring.data.rest.base-path: /rest/
info.app.name: ${spring.application.name}
info.app.description: ${spring.application.name} Server Application
info.app.version: ${spring.application.version}
#   actuator
management.info.env.enabled: true
management.endpoint.health.show-details: always #health,metrics
management.endpoints.web.exposure.include: "*"
#  swagger
springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui.html
#  zipkin-tracing
spring.zipkin.base-url: http://127.0.0.1:9411/
spring.sleuth.sampler.probability: 1.0
# Log
logging.level.org.springdoc: DEBUG
logging.level.org.springframework.web: DEBUG
logging.level.org.springframework: INFO
#trace, debug, info, warn, error, fatal, off,error #nothing but error

##1.) AUTO-UPDATED ROUTING, with
#spring.cloud.gateway.discovery.locator.enabled: true
#spring.cloud.gateway.discovery.locator.lowerCaseServiceId: true
##2.) MANUAL ROUTING
## Routes for User Service
spring.cloud.gateway.routes[0].id: MAPL-AUTHORIZATION
spring.cloud.gateway.routes[0].uri: lb://MAPL-AUTHORIZATION
spring.cloud.gateway.routes[0].predicates[0]: Path=/api/users/**

## Routes for Dashboard Service
spring.cloud.gateway.routes[1].id: MAPL-DASHBOARD
spring.cloud.gateway.routes[1].uri: lb://DASHBOARD-SERVICE
spring.cloud.gateway.routes[1].predicates[0]: Path=/api/dashboard/**

## Routes for DAILYTECH Service
spring.cloud.gateway.routes[2].id: DAILYTECH-REST
spring.cloud.gateway.routes[2].uri: lb://DAILYTECH-REST
spring.cloud.gateway.routes[2].predicates[0]: Path=/api/dailytech/**


## Routes for CRYPTOMAVEN Service
spring.cloud.gateway.routes[3].id: CRYPTOMAVEN-REST
spring.cloud.gateway.routes[3].uri: lb://CRYPTOMAVEN-REST
spring.cloud.gateway.routes[3].predicates[0]: Path=/api/cryptomaven/**

## Routes for Organization Service
spring.cloud.gateway.routes[4].id: ORGANIZATION-SERVICE
spring.cloud.gateway.routes[4].uri: lb://ORGANIZATION-SERVICE
spring.cloud.gateway.routes[4].predicates[0]: Path=/api/organizations/**

spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins: "*"
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods: GET,POST,PUT,DELETE