FROM eclipse-temurin:17

LABEL maintainer=thomas1.maestas@gmail.com

WORKDIR /app

COPY /target/mapl-service-registry-1.0.0.jar /app/mapl-service-registry.jar

ENTRYPOINT ["java","-jar","mapl-service-registry.jar"]




