build:
  version: "1.3.0"
cryptomaven:
  message: "Welcome to MAPL-INTEGRATION APIs "
  contactDetails:
    name: "Thomas Maesatas - Developer"
    email: "thomas1.maestas@gmail.com"
  dependsOn:
    - MAPL-AUTHORIZATION
  depenedencies:
    - none
####################################################

spring.application.name: MAPL-INTEGRATION
spring.application.version: 1.3.0
spring.profiles.active: local
spring.cloud.config.uri: http://localhost:8888
## Configuring info endpoint

spring.config.import: optional:configserver:http://localhost:8888
eureka.instance.client.serverUrl.defaultZone: http://localhost:8761/eureka/

info.app.name: ${spring.application.name}
info.app.description: ${spring.application.name} Server Application
info.app.version: ${spring.application.version}
management.info.env.enabled: true
management.endpoints.web.exposure.include: *

## Configuring actuator endpoints
spring.ai.openai.api-key: ${OPENAI_API_KEY}
spring.ai.openai.chat.options.model: gpt-4


logging.level.org.springdoc: DEBUG
logging.level.org.springframework.web: DEBUG

#openapi
springdoc.api-docs.path: /v3/api-docs
springdoc.swagger-ui.enabled: true
springdoc.swagger-ui.path: /swagger-ui/index.html
