build:
  version: "1.3.0"

cryptomaven:
  message: "Welcome to CRYPTO-MAVEN APIs "
  contactDetails:
    name: "Thomas Maesatas - Developer"
    email: "thomas1.maestas@gmail.com"
  dependsOn:
    - MAPL-AUTHORIZATION
  depenedencies:
    - DAILYTECH-REST
    - MAPL-NEO4J
    -
####################################################

    spring.application.name: CRYPTOMAVEN-REST
    application.version: 1.3.0
    spring.profiles.active: mysql # local  #  oracle #
    server.port: 8083

    spring.config.import: optional:configserver:http://localhost:8888
    eureka.instance.client.serverUrl.defaultZone: http://localhost:8761/eureka/

    spring.data.rest.base-path: /rest/
    ## Configuring info endpoint

    info.app.name: ${spring.application.name}
    info.app.description: ${spring.application.name} CryptoCurrency Server Application
    info.app.version: ${spring.application.version}

    management.info.env.enabled: false

    management.endpoints.web.exposure.include: health,metrics
    springdoc:
      api-docs.path: /v3/api-docs
      swagger-ui.path: /swagger-ui.html

    spring.jmx.enabled: false
    #because the javax.management.InstanceAlreadyExistsException occurs when there is an attempt to register an MBean (Managed Bean) that has already been registered. JMX is used for managing and monitoring Java applications, \
    #  and Spring Boot automatically registers various MBeans for management purposes.
    logging.level.org.springframework: info

    spring.rabbitmq.host: localhost
    spring.rabbitmq.port: 5672
    spring.rabbitmq.username: guest
    spring.rabbitmq.password: guest

    app:
      jwt-secret: e037837c23ab0fe4f59e203ece8c0ddda2c70bfd5b5319fce2af9647be43b704
      jwt-expiration-milliseconds: 604800000 # 1 week


    #spring.mvc.view.prefix=/WEB-INF/jsp
    #spring.mvc.view.suffix=.jsp
    #server.context-path=/cli

