spring.application.name: MAPL-INTEGRATION
spring.profiles.active: local
spring.cloud.config.uri: http://localhost:8888

spring.config.import: optional:configserver:http://localhost:8888
eureka.instance.client.serverUrl.defaultZone: http://localhost:8761/eureka/
eureka.client.register-with-eureka: true
eureka.client.fetch-registry: true

##  info + actuator + data-rest + zipkin-tracing + swagger endpoints
spring.data.rest.base-path: /rest/
info.app.name: ${spring.application.name}
info.app.description: ${spring.application.name} CryptoCurrency Server Application
info.app.version: ${spring.application.version}
#   actuator
management.info.env.enabled: true
management.endpoint.health.show-details: always #health,metrics
management.endpoints.web.exposure.include: "*"
#  swagger
springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui.html
#  zipkin-tracing
spring.zipkin.base-url: http://127.0.0.1:9411/
spring.sleuth.sampler.probability: 1.0
# Log
logging.level.org.springdoc: DEBUG
logging.level.org.springframework.web: DEBUG
logging.level.org.springframework: INFO
#trace, debug, info, warn, error, fatal, off,error #nothing but error


## Configuring actuator endpoints
spring.ai.openai.api-key: ${OPENAI_API_KEY}
spring.ai.openai.chat.options.model: gpt-4



#openapi
springdoc.api-docs.path: /v3/api-docs
springdoc.swagger-ui.enabled: true
springdoc.swagger-ui.path: /swagger-ui/index.html

