spring.application.name: CONFIG-SERVER
application.version: 1.3.0
server.port: 8888

eureka.instance.client.serverUrl.defaultZone: http://localhost:8761/eureka/

info.app.name: CONFIG SERVER
info.app.description: Mapl Server Application
info.app.version: 1.3.0
management.info.env.enabled: true

##### Config LOCAL Versus GITHUB
spring.profiles.active: native
#spring.profiles.active: git

spring.cloud.config.server.native.search-locations: classpath:/config
##spring.cloud.config.server.native.search-locations: file:///C://config
#spring.cloud.config.server.git.uri: https://github.com/thomasm1/config-server-repo
##### END Config LOCAL Versus GITHUB


spring.cloud.config.server.git.clone-on-start: true
#spring.cloud.config.server.git.default-label: main

logging.level.ROOT:  INFO
logging.level.org.spring.framework.cloud.config:  DEBUG

#encrypt.key: mapl