spring.application.name: MAPL-INTEGRATION
spring.profiles.active: local
spring.cloud.config.uri: http://localhost:8888
## Configuring info endpoint

spring.config.import: optional:configserver:http://localhost:8888
eureka.instance.client.serverUrl.defaultZone: http://localhost:8761/eureka/

info.app.name: MAPL-INTEGRATION
info.app.description: Mapl Server Application
info.app.version: 1.0.0
management.info.env.enabled: true
management.endpoints.web.exposure.include: "*"

## Configuring actuator endpoints
spring.ai.openai.api-key: ${OPENAI_API_KEY}
spring.ai.openai.chat.options.model: gpt-4


logging.level.org.springdoc: DEBUG
logging.level.org.springframework.web: DEBUG

#openapi
springdoc.api-docs.path: /v3/api-docs
springdoc.swagger-ui.enabled: true
springdoc.swagger-ui.path: /swagger-ui/index.html

