FROM openjdk:17-jdk-slim

LABEL maintainer=thomas1.maestas@gmail.com

COPY /target/mapl-service-registry-1.2.0.jar  mapl-service-registry.jar

ENTRYPOINT ["java","-jar","mapl-service-registry.jar"]




