--------------------------------------------------------
--  File created - Friday-November-27-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APPOINTMENT
--------------------------------------------------------

  CREATE TABLE "THOMAS"."APPOINTMENT" 
   (	"A_ID" NUMBER(10,0), 
	"C_ID" NUMBER(10,0), 
	"P_ID" NUMBER(10,0), 
	"E_ID" NUMBER(10,0), 
	"WEIGHT" NUMBER(10,0), 
	"A_DESCRIPTION" VARCHAR2(100 BYTE), 
	"TIME_SLOT" NUMBER(10,0), 
	"A_DATE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into THOMAS.APPOINTMENT
SET DEFINE OFF;
Insert into THOMAS.APPOINTMENT (A_ID,C_ID,P_ID,E_ID,WEIGHT,A_DESCRIPTION,TIME_SLOT,A_DATE) values (49,1,61,20,0,'visit with michal''s dogg',2,'2020-02-13');
Insert into THOMAS.APPOINTMENT (A_ID,C_ID,P_ID,E_ID,WEIGHT,A_DESCRIPTION,TIME_SLOT,A_DATE) values (278,1,72,21,30,'He has a stubbed toe!',3,'2020-01-28');
Insert into THOMAS.APPOINTMENT (A_ID,C_ID,P_ID,E_ID,WEIGHT,A_DESCRIPTION,TIME_SLOT,A_DATE) values (21,1,62,21,66,'Routine checkup and nail-clipping',8,'2020-01-27');
Insert into THOMAS.APPOINTMENT (A_ID,C_ID,P_ID,E_ID,WEIGHT,A_DESCRIPTION,TIME_SLOT,A_DATE) values (22,2,63,21,35,'Flea intervention and de-manging',9,'2020-01-27');
Insert into THOMAS.APPOINTMENT (A_ID,C_ID,P_ID,E_ID,WEIGHT,A_DESCRIPTION,TIME_SLOT,A_DATE) values (23,3,64,21,30,'De-worming',10,'2020-01-27');
Insert into THOMAS.APPOINTMENT (A_ID,C_ID,P_ID,E_ID,WEIGHT,A_DESCRIPTION,TIME_SLOT,A_DATE) values (24,4,65,21,35,'Blood tests',11,'2020-01-27');
Insert into THOMAS.APPOINTMENT (A_ID,C_ID,P_ID,E_ID,WEIGHT,A_DESCRIPTION,TIME_SLOT,A_DATE) values (25,5,66,21,40,'Elective cosmetic surgery',1,'2020-01-27');
Insert into THOMAS.APPOINTMENT (A_ID,C_ID,P_ID,E_ID,WEIGHT,A_DESCRIPTION,TIME_SLOT,A_DATE) values (26,6,67,21,15,'Botfly removal for youtube',2,'2020-01-27');
Insert into THOMAS.APPOINTMENT (A_ID,C_ID,P_ID,E_ID,WEIGHT,A_DESCRIPTION,TIME_SLOT,A_DATE) values (27,7,68,21,20,'Cataract removal',3,'2020-01-27');
Insert into THOMAS.APPOINTMENT (A_ID,C_ID,P_ID,E_ID,WEIGHT,A_DESCRIPTION,TIME_SLOT,A_DATE) values (28,8,61,21,3000,'Triple-bypass',4,'2020-01-27');
Insert into THOMAS.APPOINTMENT (A_ID,C_ID,P_ID,E_ID,WEIGHT,A_DESCRIPTION,TIME_SLOT,A_DATE) values (270,2,76,21,1000,'He saw a ghost!',2,'2020-01-27');
Insert into THOMAS.APPOINTMENT (A_ID,C_ID,P_ID,E_ID,WEIGHT,A_DESCRIPTION,TIME_SLOT,A_DATE) values (30,2,8,20,0,'GONNA SEE DWIGHT ABOUT JACK''S HOWLING.',2,'2020-02-13');
Insert into THOMAS.APPOINTMENT (A_ID,C_ID,P_ID,E_ID,WEIGHT,A_DESCRIPTION,TIME_SLOT,A_DATE) values (31,3,63,20,0,'Get Jabark some more meds ...',1,'2020-02-11');
Insert into THOMAS.APPOINTMENT (A_ID,C_ID,P_ID,E_ID,WEIGHT,A_DESCRIPTION,TIME_SLOT,A_DATE) values (32,5,65,20,0,'Pam complaining about Catrick :(',2,'2020-02-26');
Insert into THOMAS.APPOINTMENT (A_ID,C_ID,P_ID,E_ID,WEIGHT,A_DESCRIPTION,TIME_SLOT,A_DATE) values (163,141,153,20,0,null,1,'2020-11-26');
Insert into THOMAS.APPOINTMENT (A_ID,C_ID,P_ID,E_ID,WEIGHT,A_DESCRIPTION,TIME_SLOT,A_DATE) values (10,267,268,20,0,'GET FLEAS SEEN for JAIN ..',1,'2020-02-06');
Insert into THOMAS.APPOINTMENT (A_ID,C_ID,P_ID,E_ID,WEIGHT,A_DESCRIPTION,TIME_SLOT,A_DATE) values (9,7,67,0,0,'Gonna get Meowly (KEVIN MALONE''S) cat, a shot...',1,'2020-01-09');
Insert into THOMAS.APPOINTMENT (A_ID,C_ID,P_ID,E_ID,WEIGHT,A_DESCRIPTION,TIME_SLOT,A_DATE) values (101,6,16,20,0,'Today''s the day to save Oprah!!',3,'2020-11-27');
--------------------------------------------------------
--  DDL for Index SYS_C004225
--------------------------------------------------------

  CREATE UNIQUE INDEX "THOMAS"."SYS_C004225" ON "THOMAS"."APPOINTMENT" ("A_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table APPOINTMENT
--------------------------------------------------------

  ALTER TABLE "THOMAS"."APPOINTMENT" ADD PRIMARY KEY ("A_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
