FROM mongo:latest
LABEL maintainer="thomas1.maestas@gmail.com"

ENV MONGO_INITDB_ROOT_USERNAME=admin
ENV MONGO_INITDB_ROOT_PASSWORD=password
ENV MONGO_INITDB_DATABASE=users


COPY ./mongo-init.js /docker-entrypoint-initdb.d/

EXPOSE 27017

CMD ["mongod"]
