spring.application.name: CRYPTOMAVEN-REST
application.version: 1.3.0
spring.profiles.active: mysql # local  #  oracle #
server.port: 8083

spring.config.import: optional:configserver:http://localhost:8888
eureka.instance.client.serverUrl.defaultZone: http://localhost:8761/eureka/
eureka.client.register-with-eureka: true
eureka.client.fetch-registry: true


##  info + actuator + data-rest + zipkin-tracing + swagger endpoints
spring.data.rest.base-path: /rest/
info.app.name: ${spring.application.name}
info.app.description: ${spring.application.name} CryptoCurrency Server Application
info.app.version: ${spring.application.version}
#   actuator
management.info.env.enabled: true
management.endpoint.health.show-details: always #health,metrics
management.endpoints.web.exposure.include: "*"
#  swagger
springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui.html
#  zipkin-tracing
spring.zipkin.base-url: http://127.0.0.1:9411/
spring.sleuth.sampler.probability: 1.0
# Log
logging.level.org.springdoc: DEBUG
logging.level.org.springframework.web: DEBUG
logging.level.org.springframework: INFO
#trace, debug, info, warn, error, fatal, off,error #nothing but error

# spring.jmx.enabled: false
# because the javax.management.InstanceAlreadyExistsException occurs when there is an attempt to register an MBean (Managed Bean) that has already been registered. JMX is used for managing and monitoring Java applications, \
#  and Spring Boot automatically registers

# Spring AMQP + Actuator
spring.rabbitmq.host: localhost
spring.rabbitmq.port: 5672
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest

# Actuator endpoints for Circuit Breaker
#management.health.circuitbreakers.enabled: true

# Circuit Breaker configuration
#resilience4j.circuitbreaker.instances.AUTH-SERVICE.registerHealthIndicator: true
#resilience4j.circuitbreaker.instances.AUTH-SERVICE.failureRateThreshold: 50
#resilience4j.circuitbreaker.instances.AUTH-SERVICE.minimumNumberOfCalls: 5
#resilience4j.circuitbreaker.instances.AUTH-SERVICE.automaticTransitionFromOpenToHalfOpenEnabled: true
#resilience4j.circuitbreaker.instances.AUTH-SERVICE.waitDurationInOpenState: 5s
#resilience4j.circuitbreaker.instances.AUTH-SERVICE.permittedNumberOfCallsInHalfOpenState: 3
#resilience4j.circuitbreaker.instances.AUTH-SERVICE.slidingWindowSize: 10
#resilience4j.circuitbreaker.instances.AUTH-SERVICE.slidingWindowType: COUNT_BASED

# Retry configuration
#resilience4j.retry.instances.AUTH-SERVICE.registerHealthIndicator: true
#resilience4j.retry.instances.AUTH-SERVICE.maxRetryAttempts: 5
#resilience4j.retry.instances.AUTH-SERVICE.waitDuration: 2s
app:
  jwt-secret: e037837c23ab0fe4f59e203ece8c0ddda2c70bfd5b5319fce2af9647be43b704
  jwt-expiration-milliseconds: 604800000 # 1 week


#spring.mvc.view.prefix=/WEB-INF/jsp
#spring.mvc.view.suffix=.jsp
#server.context-path=/cli

