build:
  version: "1.3.0"
cryptomaven:
  message: "Welcome to DAILYTECH-REST APIs "
  contactDetails:
    name: "Thomas Maesatas - Developer"
    email: "thomas1.maestas@gmail.com"
  dependsOn:
    - MAPL-AUTHORIZATION
    - CRYPTOMAVEN-REST
  depenedencies:
    - none
####################################################

spring.application.name: DAILYTECH-REST
spring.application.version: 1.3.0
spring.profiles.active: mysql  # h2
server.port: 8082

spring.config.import: optional:configserver:http://localhost:8888
eureka.instance.client.serverUrl.defaultZone: http://localhost:8761/eureka/

## Configuring info endpoint
info.app.name: ${spring.application.name}
info.app.description: ${spring.application.name} Server Application
info.app.version: ${spring.application.version}

springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui.html

#because the javax.management.InstanceAlreadyExistsException occurs when there is an attempt to register an MBean (Managed Bean) that has already been registered. JMX is used for managing and monitoring Java applications, \
#  and Spring Boot automatically registers various MBeans for management purposes.

spring.rabbitmq.host: localhost
spring.rabbitmq.port: 5672
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest

app:
  jwt-secret: e037837c23ab0fe4f59e203ece8c0ddda2c70bfd5b5319fce2af9647be43b704
  jwt-expiration-milliseconds: 604800000

 ####################

#  DATA


#spring.datasource.url: jdbc:mysql://localhost:3306/test_db?createDatabaseIfNotExist=true
spring:
  datasource:
    url: jdbc:mysql://dailytech.cdkgqkcu8kyj.us-east-1.rds.amazonaws.com:3306/dailytech?useSSL=false&serverTimezone=UTC
    username: admin
    password: ${MYSQL_AWS_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        useUnicode: true
        show-sql: true
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        connection:
          characterEncoding: UTF-8
          CharSet: UTF-8
  sql:
    init:
      schema-locations: classpath:schema-mysql.sql
      data-locations: classpath:data-mysql.sql
      continue-on-error: true
      mode: never
# always #  never #

# DEV ONLY
spring.jmx.enabled: false
#because the javax.management.InstanceAlreadyExistsException occurs when there is an attempt to register an MBean (Managed Bean) that has already been registered. JMX is used for managing and monitoring Java applications, \
#  and Spring Boot automatically registers various MBeans for management purposes.
spring.jpa.hibernate.ddl-auto: none #update

## Public views
# show  bind values
logging.level.org.hibernate.type.descriptor.sql: trace
management.endpoints.web.exposure.include: "*"
management.info.env.enabled: true
logging.level.org.springframework: info
