spring.application.name: MAPL-CONFIG
application.version: 1.3.0
server.port: 8888

eureka.instance.client.serverUrl.defaultZone: http://localhost:8761/eureka/
eureka.client.register-with-eureka: true
eureka.client.fetch-registry: true

##  info + actuator + data-rest + zipkin-tracing + swagger endpoints
spring.data.rest.base-path: /rest/
info.app.name: ${spring.application.name}
info.app.description: ${spring.application.name} Server Application
info.app.version: ${spring.application.version}
#   actuator
management.info.env.enabled: true
management.endpoint.health.show-details: always #health,metrics
management.endpoints.web.exposure.include: "*"
#  zipkin-tracing
spring.zipkin.base-url: http://127.0.0.1:9411/
spring.sleuth.sampler.probability: 1.0
# Log
logging.level.ROOT:  INFO
logging.level.org.spring.framework.cloud.config:  DEBUG

##### Config LOCAL Versus GITHUB or FILESYSTEM
spring.profiles.active: native
#spring.profiles.active: git
#spring.profiles.active: local

spring.cloud.config.server.native.search-locations: classpath:/config
##spring.cloud.config.server.native.search-locations: file:///C://config
#spring.cloud.config.server.git.uri: https://github.com/thomasm1/config-server-repo
##### END Config LOCAL Versus GITHUB


spring.cloud.config.server.git.clone-on-start: true
#spring.cloud.config.server.git.default-label: main

#encrypt.key: mapl